[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4169E1"
backgroundColor = "#080D2B"
secondaryBackgroundColor = "#11173E"
textColor = "#F1F4FF"
font = "sans serif"
